<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class AppsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('apps')->insert([
             [
                'title' => '我的电脑',
                'name' => 'finder',
                'icon' =>'./images/apps/computer.png',
                'width'=>800,
                'height'=>450,
                'sort'=>1,
                'context'=>'computer',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '回收站',
                'name' => 'trash',
                'icon' =>'./images/apps/TrashIcon.png',
                'width'=>800,
                'height'=>450,
                'sort'=>2,
                'context'=>'recycle',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '系统设置',
                'name' => 'setting',
                'icon' =>'./images/apps/PrefApp.png',
                'width'=>800,
                'height'=>450,
                'sort'=>3,
                'context'=>'setting',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '应用中心',
                'name' => 'appstore',
                'icon' =>'./images/apps/appstore.png',
                'width'=>800,
                'height'=>560,
                'sort'=>4,
                'context'=>'appstore',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '控制台',
                'name' => 'terminal',
                'icon' =>'./images/apps/Terminal.png',
                'width'=>800,
                'height'=>450,
                'sort'=>5,
                'context'=>'terminal',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => 'Finder',
                'name' => 'finder',
                'icon' =>'./images/apps/Finder.png',
                'width'=>800,
                'height'=>450,
                'sort'=>6,
                'context'=>'finder',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '文本编辑器',
                'name' => 'editor',
                'icon' =>'./images/apps/Edit.png',
                'width'=>800,
                'height'=>450,
                'sort'=>7,
                'context'=>'editor',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '图片查看器',
                'name' => 'picture',
                'icon' =>'./images/apps/NSApplicationIcon.png',
                'width'=>800,
                'height'=>450,
                'sort'=>8,
                'context'=>'picture',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>2,
                'status'=>1,
             ],
             [
                'title' => '未知文件',
                'name' => 'unknown',
                'icon' =>'./images/apps/unknown.png',
                'width'=>800,
                'height'=>450,
                'sort'=>9,
                'context'=>'unknown',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => '音乐播放器',
                'name' => 'audio',
                'icon' =>'./images/apps/iTunes.png',
                'width'=>420,
                'height'=>155,
                'sort'=>10,
                'context'=>'audio',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => 'office',
                'name' => 'office',
                'icon' =>'./images/apps/office.png',
                'width'=>960,
                'height'=>600,
                'sort'=>11,
                'context'=>'office',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => '视频播放器',
                'name' => 'video',
                'icon' =>'./images/apps/iMovie.png',
                'width'=>600,
                'height'=>450,
                'sort'=>12,
                'context'=>'video',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => '游戏中心',
                'name' => 'game',
                'icon' =>'./images/apps/GameCenter.png',
                'width'=>650,
                'height'=>500,
                'sort'=>13,
                'context'=>'game',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => '文章',
                'name' => 'post',
                'icon' =>'./images/apps/word.png',
                'width'=>1280,
                'height'=>620,
                'sort'=>14,
                'context'=>'post',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => 'iCloud',
                'name' => 'icloud',
                'icon' =>'./images/apps/iCloud.png',
                'width'=>1100,
                'height'=>600,
                'sort'=>15,
                'context'=>'icloud',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
             [
                'title' => '电视直播',
                'name' => 'tv',
                'icon' =>'./images/apps/tv.png',
                'width'=>1100,
                'height'=>600,
                'sort'=>16,
                'context'=>'tv',
                'version'=>'1.0.0',
                'author'=>'tangtanglove',
                'type'=>1,
                'status'=>1,
             ],
        ]);
    }
}
