<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
             [
                'name' => 'center/index/',
                'display_name' => '系统首页',
                'description' => '系统首页',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/info',
                'display_name' => '当前用户信息',
                'description' => '获取当前用户信息',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/changePassword',
                'display_name' => '修改密码',
                'description' => '修改密码',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/index',
                'display_name' => '用户列表',
                'description' => '获取用户列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/setStatus',
                'display_name' => '设置用户状态',
                'description' => '设置单个用户状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/setAllStatus',
                'display_name' => '批量设置用户状态',
                'description' => '批量设置用户状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/store',
                'display_name' => '新增用户',
                'description' => '新增用户',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/edit',
                'display_name' => '编辑用户页面',
                'description' => '编辑用户页面',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/update',
                'display_name' => '编辑用户方法',
                'description' => '编辑用户方法',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/roles',
                'display_name' => '用户所属用户组',
                'description' => '用户所属用户组',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/user/assignRole',
                'display_name' => '分配用户组',
                'description' => '用户分配用户组',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/index',
                'display_name' => '用户组列表',
                'description' => '用户组列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/setStatus',
                'display_name' => '设置用户组状态',
                'description' => '设置用户组状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/setAllStatus',
                'display_name' => '批量设置用户组状态',
                'description' => '批量设置用户组状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/store',
                'display_name' => '新增用户组',
                'description' => '新增用户组',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/edit',
                'display_name' => '编辑用户组页面',
                'description' => '编辑用户组页面',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/update',
                'display_name' => '编辑用户组方法',
                'description' => '编辑用户组方法',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/permissions',
                'display_name' => '权限所属用户组',
                'description' => '权限所属用户组',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/role/assignPermission',
                'display_name' => '权限分配用户组',
                'description' => '将权限分配用户组',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/index',
                'display_name' => '权限列表',
                'description' => '权限列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/setStatus',
                'display_name' => '设置权限状态',
                'description' => '设置单个权限状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/setAllStatus',
                'display_name' => '批量设置权限状态',
                'description' => '批量设置权限状态',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/store',
                'display_name' => '新增权限',
                'description' => '新增权限',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/edit',
                'display_name' => '权限编辑页面',
                'description' => '权限编辑页面',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/permission/update',
                'display_name' => '权限编辑方法',
                'description' => '权限编辑方法',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/index',
                'display_name' => 'Finder首页',
                'description' => 'Finder首页',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/sidebar',
                'display_name' => '边栏列表',
                'description' => 'Finder边栏列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/openPath',
                'display_name' => '打开路径',
                'description' => 'Finder打开路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/deletePath',
                'display_name' => '删除路径',
                'description' => 'Finder删除路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/renamePath',
                'display_name' => '重命名路径',
                'description' => 'Finder重命名路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/makeDir',
                'display_name' => '创建文件夹',
                'description' => 'Finder创建文件夹',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/makeFile',
                'display_name' => '创建文件',
                'description' => 'Finder创建文件',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/emptyTrash',
                'display_name' => '清空回收站',
                'description' => 'Finder清空回收站',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/movePath',
                'display_name' => '移动路径',
                'description' => 'Finder移动路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/copyPath',
                'display_name' => '复制路径',
                'description' => 'Finder复制路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/editor/openFile',
                'display_name' => '打开文件',
                'description' => 'Editor打开文件',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/editor/saveFile',
                'display_name' => '保存文件',
                'description' => 'Editor保存文件',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/uploadFile',
                'display_name' => '上传文件',
                'description' => 'Finder上传文件',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/callbackMovePath',
                'display_name' => '回调移动路径',
                'description' => 'Finder上传文件后回调移动路径',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/finder/downloadFile',
                'display_name' => '下载文件',
                'description' => 'Finder下载文件',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/dock/index',
                'display_name' => 'Dock列表',
                'description' => 'Dock列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/wallpaper/info',
                'display_name' => '当前用户的壁纸',
                'description' => '当前用户设置的壁纸',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/wallpaper/index',
                'display_name' => '壁纸列表',
                'description' => '壁纸列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/wallpaper/setting',
                'display_name' => '设置壁纸',
                'description' => '设置壁纸',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/appstore/info',
                'display_name' => '应用的详细信息',
                'description' => '应用的详细信息',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/appstore/index',
                'display_name' => '应用列表',
                'description' => '应用列表',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/appstore/addToDesktop',
                'display_name' => '应用添加到桌面',
                'description' => '将应用添加到桌面',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],
             [
                'name' => 'center/appstore/addToDock',
                'display_name' => '应用添加到Dock',
                'description' => '将应用添加到Dock',
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
             ],


        ]);
    }
}
